services:
  claude:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    volumes:
      - type: bind
        target: /code
      - "./data/:/root/.claude"
      - "./data/claude.json:/root/claude.json"
    command: tail -f /dev/null
    environment:
      - NODE_ENV=development